#V := 1
PROJECT_NAME := example-bh1750

EXTRA_COMPONENT_DIRS := $(CURDIR)/../libs/bh1750
EXTRA_COMPONENT_DIRS += $(CURDIR)/../libs/i2cdev
EXTRA_COMPONENT_DIRS += $(CURDIR)/../libs/esp_idf_lib_helpers
include $(IDF_PATH)/make/project.mk
