PROJECT_NAME := temperature_socket

EXTRA_COMPONENT_DIRS := $(CURDIR)/../libs/connect
EXTRA_COMPONENT_DIRS += $(CURDIR)/../libs/bmp180
EXTRA_COMPONENT_DIRS += $(CURDIR)/../libs/i2cdev
EXTRA_COMPONENT_DIRS += $(CURDIR)/../libs/esp_idf_lib_helpers

include $(IDF_PATH)/make/project.mk